
try {
    throw "Error de programa"
    let x = noExiste()
    
} catch (error) {
    alert(error)
    
}
